[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://www.nitroagility.com/" target="_blank">Nitro Agility S.r.l.</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
    homeDescription = '<b>Permguard</b> is an Open Source Zero-Trust Auth* Provider for cloud-native, edge, and multi-tenant apps, <code>decoupled</code> from <code>application code</code>. It implements a centralized authorization layer using <code>Policy-as-Code</code>, enabling enforcement of permissions from anywhere, including <code>VMs</code>, <code>Containers</code>, and <code>Serverless.</code>'
    homeApplicationTitle = 'Applications'
    homeApplicationBody = 'Create and configure an <code>Application</code>, optionally including its <code>Tenants</code>.'
    homeIdentitiesTitle = "Identities"
    homeIdentitiesBody = "Create an identity source and populate it with <code>Users</code> and <code>Actors</code> using available SDKs."
    homeSchemaTitle = 'Repositories'
    homeSchemaBody = 'Create a <code>Repository</code> and configure its <code>Schema</code> (domains, resources and actions).'
    homePolicyTitle = 'Policies'
    homePolicyBody = 'Configure <code>Policies</code> to define what can be permitted or forbidden.'
    homePermissionsTitle = "Permissions"
    homePermissionsBody = "Configure <code>Permissions</code> on policies and assign them to identities (users and actors)."
    homeEnforceTitle = 'Enforce'
    homeEnforceBody = 'Enforce the permissions in the application using available SDKs.'
    docsIntroduction = 'Get Started'
